permalink: pretty

excerpt_separator: "<!--end excerpt-->"
paginate: 5
paginate_path: "blog/page/:num"

lsi: false
highlighter: rouge
markdown: kramdown

static_url: /static/
production_url : "http://docs.megaminerai.com"

include:
  - _static

exclude:
  - secret.sh*
  - s3_website.yml

gems:
  - jekyll-paginate
